config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true

  enum priority: { High: 0, Mid: 1, Low: 2}
  enum status: { Pending: 0, Processing: 1, Done: 2}

  scope :incomplete, -> { where(status: [0, 1]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  private
  def record_not_found
    render file: "#{Rails.root}/public/404.html",  
           layout: false, 
           status: 404
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, except: [:index, :new, :create]

  def index
    @tasks = Task.order(id: :desc)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)


    if @task.save
      redirect_to root_path, notice: 'Task created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to root_path, notice: 'Task updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.delete if @task
    redirect_to root_path, notice: 'Task deleted.'
  end

  private
  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title,
                                 :content,
                                 :beginning_at,
                                 :due_at,
                                 :priority,
                                 :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AteenCuman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= notice %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
<div class="row">
  <div class="col-6">
    <%= f.error_notification %>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <%= f.input :title %>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <%= f.input :beginning_at, as: :date %>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <%= f.input :due_at, as: :date %>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <%= f.input :priority, collection: Task::priorities.keys %>
  </div>
  <div class="col-3">
    <%= f.input :status, collection: Task::statuses.keys %>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <%= f.input :content %>
  </div>
</div>
  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to 'Back', tasks_path, class:'btn btn-secondary'%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1 class="text-monospace">Manage Your Task</h1>

<%= link_to '+ Add a task', new_task_path, class:'btn btn-primary text-monospace' %>

<table class="table table-dark my-1 text-monospace">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Status</th>
      <th scope="col">Priority</th>
      <th scope="col" colspan="2" class="text-center">Function</th>
    </tr>
  </thead>
  <% @tasks.each do |task| %>
  <tbody>
    <tr>
      <th><%= link_to task.title, task_path(task) %></th>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td class="text-center"><%= link_to 'Edit', edit_task_path(task) %></td>
      <td class="text-center"><%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: 'Sure to delete this?'} %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2 class="text-monospace font-weight-bold"><%= @task.title %></h2>
<table class="table table-info my-1 text-monospace">
  <tbody>
    <tr>
      <th scope="row" width="20%">Status</th>
      <td><%= @task.status %></td>
    </tr>
    <tr>
      <th scope="row" width="20%">Priority</th>
      <td><%= @task.priority %></td>
    </tr>
    <tr>
      <th scope="row" width="20%">Begin - Due</th>
      <td><%= @task.beginning_at&.strftime("%Y/%m/%d") %> - <%= @task&.due_at&.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th scope="row" width="20%">Content</th>
      <td><%= @task.content %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Back', tasks_path %>